var mysql = require('mysql');
var config = require('../../config');

var connect = mysql.createConnection(
    config.database
);

connect.connect(function (err) {
    if (err) {
        console.log(err.message);
        return;
    }
    console.log('Successfully connected Database!');
});
var provinces = [
    { "Province_ID": "0", "Province_Name":"北京市"},
    { "Province_ID": "1", "Province_Name":"天津市"},
    { "Province_ID": "2", "Province_Name":"上海市"},
    { "Province_ID": "3", "Province_Name":"重庆市"},
    { "Province_ID": "4", "Province_Name":"河北省"},
    { "Province_ID": "5", "Province_Name":"河南省"},
    { "Province_ID": "6", "Province_Name":"云南省"},
    { "Province_ID": "7", "Province_Name":"辽宁省"},
    { "Province_ID": "8", "Province_Name":"黑龙江省"},
    { "Province_ID": "9", "Province_Name":"湖南省"},
    { "Province_ID": "10", "Province_Name":"安徽省"},
    { "Province_ID": "11", "Province_Name":"山东省"},
    { "Province_ID": "12", "Province_Name":"新疆维吾尔族自治区"},
    { "Province_ID": "13", "Province_Name":"江苏省"},
    { "Province_ID": "14", "Province_Name":"浙江省"},
    { "Province_ID": "15", "Province_Name":"江西省"},
    { "Province_ID": "16", "Province_Name":"湖北省"},
    { "Province_ID": "17", "Province_Name":"广西壮族自治区"},
    { "Province_ID": "18", "Province_Name":"甘肃省"},
    { "Province_ID": "19", "Province_Name":"山西省"},
    { "Province_ID": "20", "Province_Name":"内蒙古自治区"},
    { "Province_ID": "21", "Province_Name":"陕西省"},
    { "Province_ID": "22", "Province_Name":"吉林省"},
    { "Province_ID": "23", "Province_Name":"福建省"},
    { "Province_ID": "24", "Province_Name":"贵州省"},
    { "Province_ID": "25", "Province_Name":"广东省"},
    { "Province_ID": "26", "Province_Name":"青海省"},
    { "Province_ID": "27", "Province_Name":"西藏自治区"},
    { "Province_ID": "28", "Province_Name":"四川省"},
    { "Province_ID": "29", "Province_Name":"宁夏回族自治区"},
    { "Province_ID": "30", "Province_Name":"海南省"},
    { "Province_ID": "31", "Province_Name":"台湾"},
    { "Province_ID": "32", "Province_Name":"香港"},
    { "Province_ID": "33", "Province_Name":"澳门"}
]

var city_data = [
    {"Province_ID":"0", "cities":[
        {"Area_ID":"001", "Area_Name":"东城区"},
        {"Area_ID":"002", "Area_Name":"西城区"},
        {"Area_ID":"003", "Area_Name":"崇文区"},
        {"Area_ID":"004", "Area_Name":"宣武区"},
        {"Area_ID":"005", "Area_Name":"朝阳区"},
        {"Area_ID":"006", "Area_Name":"丰台区"},
        {"Area_ID":"007", "Area_Name":"石景山区"},
        {"Area_ID":"008", "Area_Name":"海淀区"},
        {"Area_ID":"009", "Area_Name":"门头沟区"},
        {"Area_ID":"010", "Area_Name":"房山区"},
        {"Area_ID":"011", "Area_Name":"通州区"},
        {"Area_ID":"012", "Area_Name":"顺义区"},
        {"Area_ID":"013", "Area_Name":"昌平区"},
        {"Area_ID":"014", "Area_Name":"大兴区"},
        {"Area_ID":"015", "Area_Name":"怀柔区"},
        {"Area_ID":"016", "Area_Name":"平谷区"},
        {"Area_ID":"017", "Area_Name":"延庆县"},
        {"Area_ID":"018", "Area_Name":"密云县"}]},
    {"Province_ID":"1", "cities":[
        {"Area_ID":"101", "Area_Name":"滨海新区"},
        {"Area_ID":"102", "Area_Name":"和平区"},
        {"Area_ID":"103", "Area_Name":"河北区"},
        {"Area_ID":"104", "Area_Name":"河东区"},
        {"Area_ID":"105", "Area_Name":"河西区"},
        {"Area_ID":"106", "Area_Name":"南开区"},
        {"Area_ID":"107", "Area_Name":"红桥区"},
        {"Area_ID":"108", "Area_Name":"东丽区"},
        {"Area_ID":"109", "Area_Name":"西青区"},
        {"Area_ID":"110", "Area_Name":"津南区"},
        {"Area_ID":"111", "Area_Name":"北辰区"},
        {"Area_ID":"112", "Area_Name":"武清区"},
        {"Area_ID":"113", "Area_Name":"宝坻区"},
        {"Area_ID":"114", "Area_Name":"蓟县"},
        {"Area_ID":"115", "Area_Name":"静海县"},
        {"Area_ID":"116", "Area_Name":"宁河县"}]},
    {"Province_ID":"2", "cities":[
        {"Area_ID":"201", "Area_Name":"黄浦区"},
        {"Area_ID":"202", "Area_Name":"徐汇区"},
        {"Area_ID":"203", "Area_Name":"长宁区"},
        {"Area_ID":"204", "Area_Name":"静安区"},
        {"Area_ID":"205", "Area_Name":"普陀区"},
        {"Area_ID":"206", "Area_Name":"闸北区"},
        {"Area_ID":"207", "Area_Name":"虹口区"},
        {"Area_ID":"208", "Area_Name":"杨浦区"},
        {"Area_ID":"209", "Area_Name":"闵行区"},
        {"Area_ID":"210", "Area_Name":"宝山区"},
        {"Area_ID":"211", "Area_Name":"嘉定区"},
        {"Area_ID":"212", "Area_Name":"浦东新区"},
        {"Area_ID":"213", "Area_Name":"金山区"},
        {"Area_ID":"214", "Area_Name":"松江区"},
        {"Area_ID":"215", "Area_Name":"青浦区"},
        {"Area_ID":"216", "Area_Name":"奉贤区"},
        {"Area_ID":"217", "Area_Name":"崇明县"}]},
    {"Province_ID":"3", "cities":[
        {"Area_ID":"301", "Area_Name":"万州区"},
        {"Area_ID":"302", "Area_Name":"黔江区"},
        {"Area_ID":"303", "Area_Name":"涪陵区"},
        {"Area_ID":"304", "Area_Name":"渝中区"},
        {"Area_ID":"305", "Area_Name":"大渡口区"},
        {"Area_ID":"306", "Area_Name":"江北区"},
        {"Area_ID":"307", "Area_Name":"沙坪坝区"},
        {"Area_ID":"308", "Area_Name":"九龙坡区"},
        {"Area_ID":"309", "Area_Name":"南岸区"},
        {"Area_ID":"310", "Area_Name":"北碚区"},
        {"Area_ID":"311", "Area_Name":"渝北区"},
        {"Area_ID":"312", "Area_Name":"巴南区"},
        {"Area_ID":"313", "Area_Name":"长寿区"},
        {"Area_ID":"314", "Area_Name":"江津区"},
        {"Area_ID":"315", "Area_Name":"合川区"},
        {"Area_ID":"316", "Area_Name":"永川区"},
        {"Area_ID":"317", "Area_Name":"南川区"},
        {"Area_ID":"318", "Area_Name":"綦江区"},
        {"Area_ID":"319", "Area_Name":"大足区"}]},
    {"Province_ID":"4", "cities":[
        {"Area_ID":"401", "Area_Name":"石家庄市"},
        {"Area_ID":"402", "Area_Name":"唐山市"},
        {"Area_ID":"403", "Area_Name":"秦皇岛市"},
        {"Area_ID":"404", "Area_Name":"邯郸市"},
        {"Area_ID":"405", "Area_Name":"邢台市"},
        {"Area_ID":"406", "Area_Name":"保定市"},
        {"Area_ID":"407", "Area_Name":"张家口市"},
        {"Area_ID":"408", "Area_Name":"承德市"},
        {"Area_ID":"409", "Area_Name":"沧州市"},
        {"Area_ID":"410", "Area_Name":"廊坊市"},
        {"Area_ID":"411", "Area_Name":"衡水市"}]},
    {"Province_ID":"5", "cities":[
        {"Area_ID":"501", "Area_Name":"郑州市"},
        {"Area_ID":"502", "Area_Name":"开封市"},
        {"Area_ID":"503", "Area_Name":"洛阳市"},
        {"Area_ID":"504", "Area_Name":"平顶山市"},
        {"Area_ID":"505", "Area_Name":"安阳市"},
        {"Area_ID":"506", "Area_Name":"鹤壁市"},
        {"Area_ID":"507", "Area_Name":"新乡市"},
        {"Area_ID":"508", "Area_Name":"焦作市"},
        {"Area_ID":"509", "Area_Name":"濮阳市"},
        {"Area_ID":"510", "Area_Name":"许昌市"},
        {"Area_ID":"511", "Area_Name":"漯河市"},
        {"Area_ID":"512", "Area_Name":"三门峡市"},
        {"Area_ID":"513", "Area_Name":"商丘市"},
        {"Area_ID":"514", "Area_Name":"周口市"},
        {"Area_ID":"515", "Area_Name":"驻马店市"},
        {"Area_ID":"516", "Area_Name":"南阳市"},
        {"Area_ID":"517", "Area_Name":"信阳市"},
        {"Area_ID":"518", "Area_Name":"济源市"}]},
    {"Province_ID":"6", "cities":[
        {"Area_ID":"601", "Area_Name":"昆明市"},
        {"Area_ID":"602", "Area_Name":"昭通市"},
        {"Area_ID":"603", "Area_Name":"曲靖市"},
        {"Area_ID":"604", "Area_Name":"玉溪市"},
        {"Area_ID":"605", "Area_Name":"普洱市"},
        {"Area_ID":"606", "Area_Name":"保山市"},
        {"Area_ID":"607", "Area_Name":"丽江市"},
        {"Area_ID":"608", "Area_Name":"临沧市"},
        {"Area_ID":"609", "Area_Name":"楚雄彝族自治州"},
        {"Area_ID":"610", "Area_Name":"红河哈尼族彝族自治州"},
        {"Area_ID":"611", "Area_Name":"文山壮族苗族自治州"},
        {"Area_ID":"612", "Area_Name":"西双版纳傣族自治州"},
        {"Area_ID":"613", "Area_Name":"大理白族自治州"},
        {"Area_ID":"614", "Area_Name":"德宏傣族景颇族自治州"},
        {"Area_ID":"615", "Area_Name":"怒江僳僳族自治州"},
        {"Area_ID":"616", "Area_Name":"迪庆藏族自治州"}]},
    {"Province_ID":"7", "cities":[
        {"Area_ID":"701", "Area_Name":"沈阳市"},
        {"Area_ID":"702", "Area_Name":"大连市"},
        {"Area_ID":"703", "Area_Name":"鞍山市"},
        {"Area_ID":"704", "Area_Name":"抚顺市"},
        {"Area_ID":"705", "Area_Name":"本溪市"},
        {"Area_ID":"706", "Area_Name":"丹东市"},
        {"Area_ID":"707", "Area_Name":"锦州市"},
        {"Area_ID":"708", "Area_Name":"营口市"},
        {"Area_ID":"709", "Area_Name":"阜新市"},
        {"Area_ID":"710", "Area_Name":"辽阳市"},
        {"Area_ID":"711", "Area_Name":"盘锦市"},
        {"Area_ID":"712", "Area_Name":"铁岭市"},
        {"Area_ID":"713", "Area_Name":"朝阳市"},
        {"Area_ID":"714", "Area_Name":"葫芦岛市"}]},
    {"Province_ID":"8", "cities":[
        {"Area_ID":"801", "Area_Name":"哈尔滨市"},
        {"Area_ID":"802", "Area_Name":"齐齐哈尔市"},
        {"Area_ID":"803", "Area_Name":"牡丹江市"},
        {"Area_ID":"804", "Area_Name":"佳木斯市"},
        {"Area_ID":"805", "Area_Name":"大庆市"},
        {"Area_ID":"806", "Area_Name":"伊春市"},
        {"Area_ID":"807", "Area_Name":"鸡西市"},
        {"Area_ID":"808", "Area_Name":"鹤岗市"},
        {"Area_ID":"809", "Area_Name":"双鸭山市"},
        {"Area_ID":"810", "Area_Name":"七台河市"},
        {"Area_ID":"811", "Area_Name":"绥化市"},
        {"Area_ID":"812", "Area_Name":"黑河市"},
        {"Area_ID":"813", "Area_Name":"大兴安岭地区"}]},
    {"Province_ID":"9", "cities":[
        {"Area_ID":"901", "Area_Name":"长沙市"},
        {"Area_ID":"902", "Area_Name":"株洲市"},
        {"Area_ID":"903", "Area_Name":"湘潭市"},
        {"Area_ID":"904", "Area_Name":"衡阳市"},
        {"Area_ID":"905", "Area_Name":"邵阳市"},
        {"Area_ID":"906", "Area_Name":"岳阳市"},
        {"Area_ID":"907", "Area_Name":"张家界市"},
        {"Area_ID":"908", "Area_Name":"益阳市"},
        {"Area_ID":"909", "Area_Name":"常德市"},
        {"Area_ID":"910", "Area_Name":"娄底市"},
        {"Area_ID":"911", "Area_Name":"郴州市"},
        {"Area_ID":"912", "Area_Name":"永州市"},
        {"Area_ID":"913", "Area_Name":"怀化市"},
        {"Area_ID":"914", "Area_Name":"湘西土家族苗族自治州"}]},
    {"Province_ID":"10", "cities":[
        {"Area_ID":"1001", "Area_Name":"合肥市"},
        {"Area_ID":"1002", "Area_Name":"芜湖市"},
        {"Area_ID":"1003", "Area_Name":"蚌埠市"},
        {"Area_ID":"1004", "Area_Name":"淮南市"},
        {"Area_ID":"1005", "Area_Name":"马鞍山市"},
        {"Area_ID":"1006", "Area_Name":"淮北市"},
        {"Area_ID":"1007", "Area_Name":"铜陵市"},
        {"Area_ID":"1008", "Area_Name":"安庆市"},
        {"Area_ID":"1009", "Area_Name":"黄山市"},
        {"Area_ID":"1010", "Area_Name":"阜阳市"},
        {"Area_ID":"1011", "Area_Name":"宿州市"},
        {"Area_ID":"1012", "Area_Name":"滁州市"},
        {"Area_ID":"1013", "Area_Name":"六安市"},
        {"Area_ID":"1014", "Area_Name":"宣城市"},
        {"Area_ID":"1015", "Area_Name":"池州市"},
        {"Area_ID":"1016", "Area_Name":"亳州市"}]},
    {"Province_ID":"11", "cities":[
        {"Area_ID":"1101", "Area_Name":"济南市"},
        {"Area_ID":"1102", "Area_Name":"青岛市"},
        {"Area_ID":"1103", "Area_Name":"淄博市"},
        {"Area_ID":"1104", "Area_Name":"枣庄市"},
        {"Area_ID":"1105", "Area_Name":"东营市"},
        {"Area_ID":"1106", "Area_Name":"烟台市"},
        {"Area_ID":"1107", "Area_Name":"潍坊市"},
        {"Area_ID":"1108", "Area_Name":"济宁市"},
        {"Area_ID":"1109", "Area_Name":"泰安市"},
        {"Area_ID":"1110", "Area_Name":"威海市"},
        {"Area_ID":"1111", "Area_Name":"日照市"},
        {"Area_ID":"1112", "Area_Name":"滨州市"},
        {"Area_ID":"1113", "Area_Name":"德州市"},
        {"Area_ID":"1114", "Area_Name":"聊城市"},
        {"Area_ID":"1115", "Area_Name":"临沂市"},
        {"Area_ID":"1116", "Area_Name":"菏泽市"},
        {"Area_ID":"1117", "Area_Name":"莱芜市"}]},
    {"Province_ID":"12", "cities":[
        {"Area_ID":"1201", "Area_Name":"乌鲁木齐市"},
        {"Area_ID":"1202", "Area_Name":"克拉玛依市"},
        {"Area_ID":"1203", "Area_Name":"昌吉回族自治州"},
        {"Area_ID":"1204", "Area_Name":"博尔塔拉蒙古自治州"},
        {"Area_ID":"1205", "Area_Name":"伊犁哈萨克自治州"},
        {"Area_ID":"1206", "Area_Name":"巴音郭楞蒙古自治州"},
        {"Area_ID":"1207", "Area_Name":"克孜勒苏柯尔克孜自治州"},
        {"Area_ID":"1208", "Area_Name":"塔城地区"},
        {"Area_ID":"1209", "Area_Name":"阿勒泰地区"},
        {"Area_ID":"1210", "Area_Name":"吐鲁番地区"},
        {"Area_ID":"1211", "Area_Name":"哈密地区"},
        {"Area_ID":"1212", "Area_Name":"阿克苏地区"},
        {"Area_ID":"1213", "Area_Name":"喀什地区"},
        {"Area_ID":"1214", "Area_Name":"和田地区"}]},
    {"Province_ID":"13", "cities":[
        {"Area_ID":"1301", "Area_Name":"南京市"},
        {"Area_ID":"1302", "Area_Name":"无锡市"},
        {"Area_ID":"1303", "Area_Name":"徐州市"},
        {"Area_ID":"1304", "Area_Name":"常州市"},
        {"Area_ID":"1305", "Area_Name":"苏州市"},
        {"Area_ID":"1306", "Area_Name":"南通市"},
        {"Area_ID":"1307", "Area_Name":"连云港市"},
        {"Area_ID":"1308", "Area_Name":"淮安市"},
        {"Area_ID":"1309", "Area_Name":"盐城市"},
        {"Area_ID":"1310", "Area_Name":"扬州市"},
        {"Area_ID":"1311", "Area_Name":"镇江市"},
        {"Area_ID":"1312", "Area_Name":"泰州市"},
        {"Area_ID":"1313", "Area_Name":"宿迁市"}]},
    {"Province_ID":"14", "cities":[
        {"Area_ID":"1401", "Area_Name":"杭州市"},
        {"Area_ID":"1402", "Area_Name":"宁波市"},
        {"Area_ID":"1403", "Area_Name":"温州市"},
        {"Area_ID":"1404", "Area_Name":"绍兴市"},
        {"Area_ID":"1405", "Area_Name":"湖州市"},
        {"Area_ID":"1406", "Area_Name":"嘉兴市"},
        {"Area_ID":"1407", "Area_Name":"金华市"},
        {"Area_ID":"1408", "Area_Name":"衢州市"},
        {"Area_ID":"1409", "Area_Name":"台州市"},
        {"Area_ID":"1410", "Area_Name":"丽水市"},
        {"Area_ID":"1411", "Area_Name":"舟山市"}]},
    {"Province_ID":"15", "cities":[
        {"Area_ID":"1501", "Area_Name":"南昌市"},
        {"Area_ID":"1502", "Area_Name":"赣州市"},
        {"Area_ID":"1503", "Area_Name":"宜春市"},
        {"Area_ID":"1504", "Area_Name":"吉安市"},
        {"Area_ID":"1505", "Area_Name":"上饶市"},
        {"Area_ID":"1506", "Area_Name":"抚州市"},
        {"Area_ID":"1507", "Area_Name":"九江市"},
        {"Area_ID":"1508", "Area_Name":"景德镇市"},
        {"Area_ID":"1500", "Area_Name":"萍乡市"},
        {"Area_ID":"1510", "Area_Name":"新余市"},
        {"Area_ID":"1511", "Area_Name":"鹰潭市"}]},
    {"Province_ID":"16", "cities":[
        {"Area_ID":"1601", "Area_Name":"武汉市"},
        {"Area_ID":"1602", "Area_Name":"黄石市"},
        {"Area_ID":"1603", "Area_Name":"十堰市"},
        {"Area_ID":"1604", "Area_Name":"荆州市"},
        {"Area_ID":"1605", "Area_Name":"宜昌市"},
        {"Area_ID":"1606", "Area_Name":"襄阳市"},
        {"Area_ID":"1607", "Area_Name":"鄂州市"},
        {"Area_ID":"1608", "Area_Name":"荆门市"},
        {"Area_ID":"1609", "Area_Name":"黄冈市"},
        {"Area_ID":"1610", "Area_Name":"孝感市"},
        {"Area_ID":"1611", "Area_Name":"咸宁市"},
        {"Area_ID":"1612", "Area_Name":"随州市"},
        {"Area_ID":"1613", "Area_Name":"恩施土家族苗族自治州"}]},
    {"Province_ID":"17", "cities":[
        {"Area_ID":"1701", "Area_Name":"南宁市"},
        {"Area_ID":"1702", "Area_Name":"柳州市"},
        {"Area_ID":"1703", "Area_Name":"桂林市"},
        {"Area_ID":"1704", "Area_Name":"梧州市"},
        {"Area_ID":"1705", "Area_Name":"北海市"},
        {"Area_ID":"1706", "Area_Name":"崇左市"},
        {"Area_ID":"1707", "Area_Name":"来宾市"},
        {"Area_ID":"1708", "Area_Name":"贺州市"},
        {"Area_ID":"1709", "Area_Name":"玉林市"},
        {"Area_ID":"1710", "Area_Name":"百色市"},
        {"Area_ID":"1711", "Area_Name":"河池市"},
        {"Area_ID":"1712", "Area_Name":"钦州市"},
        {"Area_ID":"1713", "Area_Name":"防城港市"},
        {"Area_ID":"1714", "Area_Name":"贵港市"}]},
    {"Province_ID":"18", "cities":[
        {"Area_ID":"1801", "Area_Name":"兰州市"},
        {"Area_ID":"1802", "Area_Name":"嘉峪关市"},
        {"Area_ID":"1803", "Area_Name":"金昌市"},
        {"Area_ID":"1804", "Area_Name":"白银市"},
        {"Area_ID":"1805", "Area_Name":"天水市"},
        {"Area_ID":"1806", "Area_Name":"酒泉市"},
        {"Area_ID":"1807", "Area_Name":"张掖市"},
        {"Area_ID":"1808", "Area_Name":"武威市"},
        {"Area_ID":"1809", "Area_Name":"定西市"},
        {"Area_ID":"1810", "Area_Name":"陇南市"},
        {"Area_ID":"1811", "Area_Name":"平凉市"},
        {"Area_ID":"1812", "Area_Name":"庆阳市"},
        {"Area_ID":"1813", "Area_Name":"临夏回族自治州"},
        {"Area_ID":"1814", "Area_Name":"甘南藏族自治州"}]},
    {"Province_ID":"19", "cities":[
        {"Area_ID":"1901", "Area_Name":"太原市"},
        {"Area_ID":"1902", "Area_Name":"大同市"},
        {"Area_ID":"1903", "Area_Name":"阳泉市"},
        {"Area_ID":"1904", "Area_Name":"长治市"},
        {"Area_ID":"1905", "Area_Name":"晋城市"},
        {"Area_ID":"1906", "Area_Name":"朔州市"},
        {"Area_ID":"1907", "Area_Name":"忻州市"},
        {"Area_ID":"1908", "Area_Name":"吕梁市"},
        {"Area_ID":"1909", "Area_Name":"晋中市"},
        {"Area_ID":"1910", "Area_Name":"临汾市"},
        {"Area_ID":"1911", "Area_Name":"运城市"}]},
    {"Province_ID":"20", "cities":[
        {"Area_ID":"2001", "Area_Name":"呼和浩特市"},
        {"Area_ID":"2002", "Area_Name":"包头市"},
        {"Area_ID":"2003", "Area_Name":"乌海市"},
        {"Area_ID":"2004", "Area_Name":"赤峰市"},
        {"Area_ID":"2005", "Area_Name":"呼伦贝尔市"},
        {"Area_ID":"2006", "Area_Name":"通辽市"},
        {"Area_ID":"2007", "Area_Name":"乌兰察布市"},
        {"Area_ID":"2008", "Area_Name":"鄂尔多斯市"},
        {"Area_ID":"2009", "Area_Name":"巴彦淖尔市"},
        {"Area_ID":"2010", "Area_Name":"兴安盟"},
        {"Area_ID":"2011", "Area_Name":"锡林郭勒盟"},
        {"Area_ID":"2012", "Area_Name":"阿拉善盟"}]},
    {"Province_ID":"21", "cities":[
        {"Area_ID":"2101", "Area_Name":"西安市"},
        {"Area_ID":"2102", "Area_Name":"铜川市"},
        {"Area_ID":"2103", "Area_Name":"宝鸡市"},
        {"Area_ID":"2104", "Area_Name":"咸阳市"},
        {"Area_ID":"2105", "Area_Name":"渭南市"},
        {"Area_ID":"2106", "Area_Name":"汉中市"},
        {"Area_ID":"2107", "Area_Name":"安康市"},
        {"Area_ID":"2108", "Area_Name":"商洛市"},
        {"Area_ID":"2109", "Area_Name":"延安市"},
        {"Area_ID":"2110", "Area_Name":"榆林市"}]},
    {"Province_ID":"22", "cities":[
        {"Area_ID":"2201", "Area_Name":"长春市"},
        {"Area_ID":"2202", "Area_Name":"吉林市"},
        {"Area_ID":"2203", "Area_Name":"四平市"},
        {"Area_ID":"2204", "Area_Name":"辽源市"},
        {"Area_ID":"2205", "Area_Name":"通化市"},
        {"Area_ID":"2206", "Area_Name":"白山市"},
        {"Area_ID":"2207", "Area_Name":"白城市"},
        {"Area_ID":"2208", "Area_Name":"松原市"},
        {"Area_ID":"2209", "Area_Name":"延边朝鲜族自治州"}]},
    {"Province_ID":"23", "cities":[
        {"Area_ID":"2301", "Area_Name":"福州市"},
        {"Area_ID":"2302", "Area_Name":"莆田市"},
        {"Area_ID":"2303", "Area_Name":"泉州市"},
        {"Area_ID":"2304", "Area_Name":"厦门市"},
        {"Area_ID":"2305", "Area_Name":"漳州市"},
        {"Area_ID":"2306", "Area_Name":"龙岩市"},
        {"Area_ID":"2307", "Area_Name":"三明市"},
        {"Area_ID":"2308", "Area_Name":"南平市"},
        {"Area_ID":"2309", "Area_Name":"宁德市"}]},
    {"Province_ID":"24", "cities":[
        {"Area_ID":"2401", "Area_Name":"贵阳市"},
        {"Area_ID":"2402", "Area_Name":"六盘水市"},
        {"Area_ID":"2403", "Area_Name":"遵义市"},
        {"Area_ID":"2404", "Area_Name":"铜仁市"},
        {"Area_ID":"2405", "Area_Name":"毕节市"},
        {"Area_ID":"2406", "Area_Name":"安顺市"},
        {"Area_ID":"2407", "Area_Name":"黔西南布依族苗族州"},
        {"Area_ID":"2408", "Area_Name":"黔东南苗族侗族州"},
        {"Area_ID":"2409", "Area_Name":"黔南布依族苗族州"}]},
    {"Province_ID":"25", "cities":[
        {"Area_ID":"2501", "Area_Name":"广州市"},
        {"Area_ID":"2502", "Area_Name":"深圳市"},
        {"Area_ID":"2503", "Area_Name":"珠海市"},
        {"Area_ID":"2504", "Area_Name":"汕头市"},
        {"Area_ID":"2505", "Area_Name":"佛山市"},
        {"Area_ID":"2506", "Area_Name":"韶关市"},
        {"Area_ID":"2507", "Area_Name":"湛江市"},
        {"Area_ID":"2508", "Area_Name":"肇庆市"},
        {"Area_ID":"2509", "Area_Name":"江门市"},
        {"Area_ID":"2510", "Area_Name":"茂名市"},
        {"Area_ID":"2511", "Area_Name":"惠州市"},
        {"Area_ID":"2512", "Area_Name":"梅州市"},
        {"Area_ID":"2513", "Area_Name":"汕尾市"},
        {"Area_ID":"2514", "Area_Name":"河源市"},
        {"Area_ID":"2515", "Area_Name":"阳江市"},
        {"Area_ID":"2516", "Area_Name":"清远市"},
        {"Area_ID":"2517", "Area_Name":"东莞市"},
        {"Area_ID":"2518", "Area_Name":"中山市"},
        {"Area_ID":"2519", "Area_Name":"潮州市"},
        {"Area_ID":"2520", "Area_Name":"揭阳市"},
        {"Area_ID":"2521", "Area_Name":"云浮市"}]},
    {"Province_ID":"26", "cities":[
        {"Area_ID":"2601", "Area_Name":"西宁市"},
        {"Area_ID":"2602", "Area_Name":"海东市"},
        {"Area_ID":"2603", "Area_Name":"海北藏族自治州"},
        {"Area_ID":"2604", "Area_Name":"黄南藏族自治州"},
        {"Area_ID":"2605", "Area_Name":"海南藏族自治州"},
        {"Area_ID":"2606", "Area_Name":"果洛藏族自治州"},
        {"Area_ID":"2607", "Area_Name":"玉树藏族自治州"},
        {"Area_ID":"2608", "Area_Name":"海西蒙古族藏族自治州"}]},
    {"Province_ID":"27", "cities":[
        {"Area_ID":"2701", "Area_Name":"拉萨市"},
        {"Area_ID":"2702", "Area_Name":"日喀则市"},
        {"Area_ID":"2703", "Area_Name":"昌都地区"},
        {"Area_ID":"2704", "Area_Name":"山南地区"},
        {"Area_ID":"2705", "Area_Name":"那曲地区"},
        {"Area_ID":"2706", "Area_Name":"阿里地区"},
        {"Area_ID":"2707", "Area_Name":"林芝地区"}]},
    {"Province_ID":"28", "cities":[
        {"Area_ID":"2801", "Area_Name":"成都市"},
        {"Area_ID":"2802", "Area_Name":"绵阳市"},
        {"Area_ID":"2803", "Area_Name":"自贡市"},
        {"Area_ID":"2804", "Area_Name":"攀枝花市"},
        {"Area_ID":"2805", "Area_Name":"泸州市"},
        {"Area_ID":"2806", "Area_Name":"德阳市"},
        {"Area_ID":"2807", "Area_Name":"广元市"},
        {"Area_ID":"2808", "Area_Name":"遂宁市"},
        {"Area_ID":"2809", "Area_Name":"内江市"},
        {"Area_ID":"2810", "Area_Name":"乐山市"},
        {"Area_ID":"2811", "Area_Name":"资阳市"},
        {"Area_ID":"2812", "Area_Name":"宜宾市"},
        {"Area_ID":"2813", "Area_Name":"南充市"},
        {"Area_ID":"2814", "Area_Name":"达州市"},
        {"Area_ID":"2815", "Area_Name":"雅安市"},
        {"Area_ID":"2816", "Area_Name":"广安市"},
        {"Area_ID":"2817", "Area_Name":"巴中市"},
        {"Area_ID":"2818", "Area_Name":"眉山市"},
        {"Area_ID":"2819", "Area_Name":"阿坝藏族羌族自治州"},
        {"Area_ID":"2820", "Area_Name":"甘孜藏族自治州"},
        {"Area_ID":"2821", "Area_Name":"凉山彝族自治州"}]},
    {"Province_ID":"29", "cities":[
        {"Area_ID":"2901", "Area_Name":"银川市"},
        {"Area_ID":"2902", "Area_Name":"石嘴山市"},
        {"Area_ID":"2903", "Area_Name":"吴忠市"},
        {"Area_ID":"2904", "Area_Name":"固原市"},
        {"Area_ID":"2905", "Area_Name":"中卫市"}]},
    {"Province_ID":"30", "cities":[
        {"Area_ID":"3001", "Area_Name":"海口市"},
        {"Area_ID":"3002", "Area_Name":"三亚市"},
        {"Area_ID":"3003", "Area_Name":"三沙市"}]},
    {"Province_ID":"31", "cities":[
        {"Area_ID":"3101", "Area_Name":"台北市"},
        {"Area_ID":"3102", "Area_Name":"新北市"},
        {"Area_ID":"3103", "Area_Name":"台中市"},
        {"Area_ID":"3104", "Area_Name":"台南市"},
        {"Area_ID":"3105", "Area_Name":"高雄市"}]},
    {"Province_ID":"32", "cities":[
        {"Area_ID":"3201", "Area_Name":"中西区"},
        {"Area_ID":"3202", "Area_Name":"东区"},
        {"Area_ID":"3203", "Area_Name":"九龙城区"},
        {"Area_ID":"3204", "Area_Name":"观塘区"},
        {"Area_ID":"3205", "Area_Name":"南区"},
        {"Area_ID":"3206", "Area_Name":"深水埗区"},
        {"Area_ID":"3207", "Area_Name":"黄大仙区"},
        {"Area_ID":"3208", "Area_Name":"湾仔区"},
        {"Area_ID":"3209", "Area_Name":"油尖旺区"},
        {"Area_ID":"3210", "Area_Name":"离岛区"},
        {"Area_ID":"3211", "Area_Name":"葵青区"},
        {"Area_ID":"3212", "Area_Name":"北区"},
        {"Area_ID":"3213", "Area_Name":"西贡区"},
        {"Area_ID":"3214", "Area_Name":"沙田区"},
        {"Area_ID":"3215", "Area_Name":"屯门区"},
        {"Area_ID":"3216", "Area_Name":"大埔区"},
        {"Area_ID":"3217", "Area_Name":"荃湾区"},
        {"Area_ID":"3218", "Area_Name":"元朗区"}]},
    {"Province_ID":"33", "cities":[
        {"Area_ID":"3301", "Area_Name":"花地玛堂区"},
        {"Area_ID":"3302", "Area_Name":"圣安多尼堂区"},
        {"Area_ID":"3303", "Area_Name":"大堂区"},
        {"Area_ID":"3304", "Area_Name":"望德堂区"},
        {"Area_ID":"3305", "Area_Name":"风顺堂区"},
        {"Area_ID":"3306", "Area_Name":"嘉模堂区"},
        {"Area_ID":"3307", "Area_Name":"圣方济各堂区"}]}
]


provinces.forEach(function (ele,i) {
    connect.query('INSERT INTO Province SET ?', ele, function (err, rows) {
        if(err) {
            console.log(err.message);
        }
    })
})

city_data.forEach(function (ele,i) {
    //var ele.
    var cities = ele.cities;
    cities.forEach(function (city,i) {
        city.Province_ID = ele.Province_ID;
        connect.query('INSERT INTO Area SET ?', city, function (err, rows) {
            if(err) {
                console.log(err.message);
            }
        })
    })

})
