<?php
    $password=$_POST["password"];
	$username=$_POST['username'];
	$token=$_POST['token'];
    $response["msg"]=0;
	$response["Province_ID"]=1;
    $response["Province_Name"]="北京";
    $response["Credit_Rank"]=3;
    $response["User_Name"]="耿金坤";
    $response["User_ID"]=2;
	$response["Credit_Rank"]=3;
	$response["isUser_1"]=1;
    $response["Area_ID"]="1";
    $response["Area_Name"]='海淀区';
    $response["Identity_ID"]="371581199409060051";
    $response["Appointment_Limit"]=1;
	$response["Sex"]=1;
	$response["isUser_1"]=1;
    $response["Birthday"]="1994-09-06";
    $response["Location"]='北京航空航天大学';
    $response["Identity_ID"]="371581199409060051";
    $response["Phone"]="13260129923";
	$response["Mail"]="steam1994@163.com";
	echo json_encode($response);
?>